# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ec171ee84dcfe100669a1271ebebb2ecb705fb817e9bfb10cdaf0062da35c414611db3e72a7618d61b278825a1c23bb5e340e280351f1f4d6f31c627f85e3eb

test:
  secret_key_base: c011a160fd0fdef2ac3b0fe72ac26852f0975ef0a715b1b951604c8bc42b02f428839681e6b60024a11dd4d635024c00557eeddcc876c11e59cab0384c1d4635

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
